### ISSUE TITLE
Update API documentation on enum parameters

### ISSUE THREAD

**Issue by k-guilbert** [sencrop/sencrop-developer-platform#8]
Some requests to the API are now not possible due to enum restriction that was not in place before.

We need to : 
- Update the documentation to notify the users that some parameters are limited.
- Update code samples for daily, hourly and raw datas that are also not valid now.

**Comment by nfroidure** [comment]
Fixed by a Swagger UI update 
![image](https://user-images.githubusercontent.com/229633/40060992-2d5dd7d0-5858-11e8-9633-d02175f4a2ea.png)
